### ISSUE TITLE
Pagination links get funky when reaching triple digits

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-frontend#101]
## Summary of Bug

:eyes_bleeding:
<img width="258" alt="Screen Shot 2021-06-04 at 1 59 59 PM" src="https://user-images.githubusercontent.com/1687233/120856468-c809f880-c534-11eb-858f-aab058504ebc.png">

## Version

current

## Steps to Reproduce

1. Find a table with a lot of data and click through till you get to 100.
1. Behold the glory of overlapping links.

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Shomy032** [comment]
I fixed it , can you review my pull request.

**Comment by Shomy032** [comment]
@webbushka   i have changed my pull request , can you review?
