### ISSUE TITLE
IBC List View

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-frontend#131]
## Summary

Add a list view page for IBCs

## Problem Definition

We need a way for the IBCs to be viewed

## Proposal

- [ ] Create new page
- [ ] Pull IBC list
- [ ] Display list
- [ ] Table with following columns
  - Name
  - Total Supply
  - Last Tx
  - Age
- [ ] Add new url and assign to the list view

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jarrydallison** [comment]
Closed by PR #257
