### ISSUE TITLE
Add governance tx list to validator screen

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-frontend#140]
## Summary

Add a tabbable list card and the initial list should be goverance tx list associated with the validator's operator address

## Problem Definition

Need to see governance txs for a validator

## Proposal

Columns should be similar to https://cosmoshub.iobscan.io/#/staking/cosmosvaloper1fghgwhgtxtcshj4a9alp7u2qv6n2wffqhpxcnk

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by VigM-Figure** [comment]
Needs API built out
