### ISSUE TITLE
Tx history widget on dashboard is broken on FF

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-frontend#145]
## Summary of Bug 

On the dashboard page there is a tx history widget that has a filter above that should change the graph when dates are put in. It appears to be broken in FF.

## Version

2.0.1

## Steps to Reproduce

* Open page in FF
* fill out form
* hit apply
* observe nothing happens

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by VigM-Figure** [comment]
This is an issue anywhere there are dates.  Firefox is having issues processing the date values:
```Uncaught RangeError: invalid date
    to getUTCTime.js:9```
   
   Should be a single fix to take care of any FF date issues across the app

**Comment by VigM-Figure** [comment]
PR: https://github.com/provenance-io/explorer-frontend/pull/151
