### ISSUE TITLE
Delegations Transactions Export

### ISSUE THREAD

**Issue by joshmislas** [provenance-io/explorer-frontend#150]
## Summary

Need the ability to export transaction log of all fees collected by validators (specifically Figure's validators) as well as subsequent allocation to delegators (amounts, dates, wallet addresses)

## Problem Definition

Need way for finance/accounting to record and reconcile hash "revenue" coming in to Figure as a validator. Currently no way to export data as csv/excel or visualize without clicking through several pages in Provenance explorer and manually compiling.  This will allow us to ensure Figure is correctly accounting for all received hash fees. 

At its most basic, need to be able to point to how much revenue we've gotten as a validator in a given period

## Proposal

Add button to download export from the Delegation Transactions section in https://explorer.provenance.io/validator. Screenshot attached:

![image](https://user-images.githubusercontent.com/86630930/123706852-acd19680-d81d-11eb-8fd1-acfa1aee500a.png)

Export file should be in csv/xlsx format and contain date/time, receiving wallet address, amount, status

Need something that shows: 

- validator got x.xx amount of hash for period and then that hash was allocated to x,y,z addresses and each got y.yy amount of hash.

or alternatively, 2 separate reports: 
- one which shows the hash the validator is receiving 
- another which shows, over a given period, which addresses got which amount of hash from that validator .

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by VigM-Figure** [comment]
_Self Note:_
- Will need to work with Explorer-Service to create an API to gather all the data in a single request (vs a paginated request)

**Comment by iramiller** [comment]
This is actually an extremely complex process to calculate... what is requires is the staking power associated with each address, which delegator they are associated with, the community pool rate, bonus rate (and applicability based on signatures collected for the block), and the particulars of the validator's commission rate at the time each block is cut.  Using these values it is possible to break down the fees paid in each block to a single amount accrued by each address.

This same process is what would be required to build a "pie graph" that could display a drill down of where the fees paid are going for each block.

**Comment by jarrydallison** [comment]
This has been deemed outside the scope of the Provenance Explorer website. Provenance encourages additional development outside of Explorer to provide this service.
