### ISSUE TITLE
Explorer shows address in public key field

### ISSUE THREAD

**Issue by vwagner** [provenance-io/explorer-frontend#198]
## Summary of Bug

The "Account Details" view of Explorer is showing the address for the account in the field labeled `Public Key`. 

Example:
https://explorer.provenance.io/accounts/pb1q4jdcwg350cqsdzn6jy8fxln9mx5rg7dm5mzs7

<img width="1229" alt="Screen Shot 2021-11-02 at 10 05 04 PM" src="https://user-images.githubusercontent.com/2718509/140008683-297a51f2-e9cf-45fd-8d9c-13dfb97e9cdb.png">

## Version

v2.2.4

## Steps to Reproduce

Search for & view any address in the Explorer. The data values for fields "address" and "public key" are currently identical (showing the address value, not the public key).

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by minxylynx** [comment]
This will need an FE change, but the data itself will need BE changes.
