### ISSUE TITLE
Bug: Remove rounding on hash USD price on dashboard

### ISSUE THREAD

**Issue by minxylynx** [provenance-io/explorer-frontend#202]
## Summary of Bug

The USD hash price should be displayed as 3 decimal places, as it comes through on the price API.

![image](https://user-images.githubusercontent.com/9067643/144500985-6ba815d9-a4dd-4617-b58d-9d1d0a8e6230.png)

vs 

`curl https://www.dlob.io/gecko/external/api/v1/exchange/tickers | jq`

```
[
  {
    "tickerId": "HASH_USD",
    "baseCurrency": "HASH",
    "targetCurrency": "USD",
    "lastPrice": 0.119,
    "baseVolume": 295980,
    "targetVolume": 35179.24,
    "bid": 0.117,
    "ask": 0.119,
    "high": 0.119,
    "low": 0.118
  }
]
```

## Version

latest

## Steps to Reproduce

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by Villian79** [comment]
Hello! May I ask for permission to contribute to the project @minxylynx ?
I've completed the steps below to reproduce and fix this issue:
- Cloned the latest version and installed deps
-  In BlockSpotlight.js on line 165 made the following change:
```diff
-decimal: 2,
+decimal: 3,
```
- Created `Villian79/202/price-rounding` branch locally ready to commit

**Comment by minxylynx** [comment]
@Villian79 of course! Make sure you assign yourself to the issue as well.

@webbushka FYI

**Comment by Villian79** [comment]
#

**Comment by Villian79** [comment]
@webbushka Created PR #207, but could not assign an issue to myself. Maybe someone can assist me with that?

**Comment by jarrydallison** [comment]
@Villian79 Just assigned this to you. Thanks!
