### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-frontend#203]
## Summary of Bug

Account Type is spelled wrong on the account details page

![image](https://user-images.githubusercontent.com/1687233/145491320-d377fa97-c74a-4670-afe8-faa748899d0a.png)

## Version

v2.2.4

## Steps to Reproduce

* Go to any account detail page (ex https://explorer.test.provenance.io/accounts/tp143sel8w3rshuz7a5jwtq7k4nrgp60tv846kgyr)

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by github4maninder** [comment]
Hi, I would like to fix this issue.
