### ISSUE TITLE
Feature: Add page for chain versions

### ISSUE THREAD

**Issue by minxylynx** [provenance-io/explorer-frontend#208]
## Summary

Add a page that holds the current list of versions and info against the chain.

## Proposal

- [x] Add `Stats` top bar menu item
- [x] Add page `Versions` under Stats
- [x] Using `/api/v2/chain/upgrades` API, add a table showing:
  - [x] Upgrade Height
  - [x] Upgrade Name
  - [x] Initial version -> info defining initial as the one submitted with the upgrade proposal
  - [x] Current Version -> current patch version that can be applied at this upgrade height
  - [x] Skipped -> show a checkmark or something denoting it skipped, info defining it like this https://github.com/provenance-io/testnet/blob/main/README.md?plain=1#L48
  - [x] Schedules -> show a checkmark or something denoting it scheduled, info defining scheduled as `not yet applied - will be applied at upgrade height`

API response: 
```
[
  {
      "upgradeHeight": 0,
      "upgradeName": "Genesis",
      "definedVersion": "v0.2.0",
      "currentPatchVersion": "v0.2.1",
      "skipped": false,
      "scheduled": false
    }
]
```

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by minxylynx** [comment]
NOTE: we may abandon `Initial Version` because the `Current Version` should be the one people use out of the gate.

**Comment by jarrydallison** [comment]
@minxylynx for bullet two, instead of adding a page for each stat, what about matching a similar construct to the dashboard view, that allows a user to scroll up/down and view all stats on one page
![Screen Shot 2021-12-16 at 2 23 46 PM](https://user-images.githubusercontent.com/90670725/146450976-6c41001a-314d-4ba3-a6c8-53c90ec48347.png)
?

**Comment by iramiller** [comment]
I agree that abandoning the "initial version" ... and going with "Recommended Version" makes the most sense here... in some cases (such as early 1.7.x releases) the initial version(s) should not be used at all...

**Comment by iramiller** [comment]
The skipped part could be a bit more clear as well ... perhaps if the line was in strikethrough italics that would help? Perhaps with one of those info hovers that indicates the upgrade height should be skipped ... but even if they tried to run that upgrade using the recommended 1.7.6 version it would actually halt immediately and tell them to skip the upgrade height

Combining "recommended versions" with a more obvious ~abandoned version~ should be really easy to follow.

**Comment by minxylynx** [comment]
@jarrydallison  ehh, Maybe for now its fine (with just the upgrades on the stats page), but ideally we add additional stats related to gas usage / fees as well as param sets for the chain. Adding all different types of stats to one page can get confusing

**Comment by minxylynx** [comment]
> The skipped part could be a bit more clear as well ... perhaps if the line was in strikethrough italics that would help? Perhaps with one of those info hovers that indicates the upgrade height should be skipped ... but even if they tried to run that upgrade using the recommended 1.7.6 version it would actually halt immediately and tell them to skip the upgrade height
> 
> Combining "recommended versions" with a more obvious ~abandoned version~ should be really easy to follow.

@iramiller @jarrydallison  I agree on "Recommended Version" instead of both "Initial" and "Current" columns.  

How about consolidating the "Skipped" and "Scheduled" columns into one column that shows "Skipped"  (with a clickable info icon that shows how to skip that upgrade) or "Scheduled". Maybe have fancy text for each, but dunno what. Also, could ask @webbushka about the color Hexcodes... maybe we could use those somehow.

**Comment by jarrydallison** [comment]
@minxylynx @iramiller I believe I've implemented all the comments you've posted. Take a look and let me know what you think.
<img width="1697" alt="Screen Shot 2021-12-21 at 5 27 34 PM" src="https://user-images.githubusercontent.com/90670725/147014886-06cb69be-9020-4b39-a992-d1e76ac76bbe.png">
