### ISSUE TITLE
Enhancement: Update smart linking for addresses

### ISSUE THREAD

**Issue by minxylynx** [provenance-io/explorer-frontend#259]
## Summary

For some addresses, we link to the detail page it refers to. It would be nice to have this apply to all applicable addresses across the platform.

## Proposal

* Link addresses for accounts, validators, scopes, contracts and governance proposals
  - [ ] accounts: `tp` / `pb`
  - [ ] validators: `tpvaloper` / `pbvaloper`
  - [ ] scopes: `scope`
  - [ ] contract: `tp` / `pb`
    - will add `isContract` flag to response where necessary
  - [ ] governance proposals: Only applicable in a few tables, identified by `proposalId` or `proposal_id`
____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by jarrydallison** [comment]
Closed via #327
