### ISSUE TITLE
Minor improvements to announcements

### ISSUE THREAD

**Issue by jarrydallison** [provenance-io/explorer-frontend#340]
## Summary

Minor improvements to the new announcements feature

## Problem Definition

Feedback has been great, just want to incorporate it.

## Proposal

- Remove extra "X" from the main content holder for announcements. Only use "X" in the datacards
- Change icon to megaphone or bell (bell is more common)
- Add hover to menu icons (announcements and login)

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by ahatzz11** [comment]
Regarding the X - How often do we expect announcements to happen? If there's a bunch I think it would be annoying to have to manage each one, maybe on the main content holder there could be a `clear all announcements` text or something if there is >1 announcement? Just a thought!

**Comment by jarrydallison** [comment]
@ahatzz11 I just changed it to have a "Close All" button, no matter how many announcements there are. I think it looks fine and makes sense at this stage.
