### ISSUE TITLE
Issues with dlob gecko requires additional error handling

### ISSUE THREAD

**Issue by jarrydallison** [provenance-io/explorer-frontend#375]
## Summary of Bug

If dlob gecko goes down, there is no error handling built in for this. We need to add better error handling for 500s.

## Version

Current (3.1.1)

## Steps to Reproduce

This is difficult, but in the event the dlob does not provide data, we can see the result on the dashboard
<img width="1279" alt="Screen Shot 2022-07-05 at 9 02 50 AM" src="https://user-images.githubusercontent.com/90670725/177358604-1ae5b553-6c83-4e20-9616-6bf75ff3730f.png">

____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by minxylynx** [comment]
Fixed by moving to CMC api
