### ISSUE TITLE
Update tx message ui

### ISSUE THREAD

**Issue by crussell-figure** [provenance-io/explorer-frontend#50]
## Summary

Right now, the tx messages arent being shown properly. They should be.

## Problem Definition

currently, [tx query](https://service-explorer.test.provenance.io/api/v2/txs/125FCD2CA60EE2B3DA3470720A74F9A5752E422AE73F1FC5EF2D3238C9E95FF7) returns a msg object that is a list of messages. They are not being displayed properly due to the differences in objects. 

[how it currently looks ](https://explorer.test.provenance.io/tx/125FCD2CA60EE2B3DA3470720A74F9A5752E422AE73F1FC5EF2D3238C9E95FF7)
[how it should look](https://stargate.iobscan.io/#/tx?txHash=CA1592B34E1435B835147108384FB4A0D10034EA65B165A381BE64AAD7A000EE)

## Proposal

There should be an easy, generic way to just map over the object fields and print the field to value for each msg object. 

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by webbushka** [comment]
this was duplicated by #90
