### ISSUE TITLE
Explorer UI Bugs Part 2

### ISSUE THREAD

**Issue by webbushka** [provenance-io/explorer-frontend#55]
## Block:
- [x] Validator voting power percentages are wrong

## Tx:
- [x] Remove hash conversion (Fee)
- [ ] Nice to Have: Translate the msg list into proper UI objects (#50)

## Validators:
* list
	- [x] voting power percentages arent right
	- [x] jailed/candidate list has slightly different columns
		* example: https://cosmoshub.iobscan.io/#/staking
* single
	- [x] remove hash conversion (bonded tokens, rewards)
	- [x] candidate/jailed validators have different layouts/expect different info
		* example: https://cosmoshub.iobscan.io/#/staking/cosmosvaloper19kwwdw0j64xhrmgkz49l0lmu5uyujjayxakwsn
               https://cosmoshub.iobscan.io/#/staking/cosmosvaloper1kgquh04ffqvadekf6e47070gskm0s0h28cl7ht

## Accounts:
- [x] point the balance denom query towards the new queryDenom value instead of the display value

## Assets:
* See https://github.com/provenance-io/explorer-service/pull/69 for additional changes
* list 
	- [x] Owner is now "holdingAccount", as owner is a list, not a single
* single
	- [x] owner = holdingAccount
	- [x] add managers = managingAccounts
	- [x] holders is now a paginated list

**Comment by crussell-figure** [comment]
Adding -> Block: Proposer should show the moniker, not the address. Comes from the block detail.

Also, why is `/blocks/height` being called on the Block page?

**Comment by webbushka** [comment]
> Also, why is `/blocks/height` being called on the Block page?

`/blocks/height` is used on the block page to make the prev / next block functionality on the header

<img width="413" alt="Screen Shot 2021-04-28 at 11 26 38 AM" src="https://user-images.githubusercontent.com/1687233/116474746-c0687d00-a82d-11eb-9256-68691c4d603b.png">

**Comment by crussell-figure** [comment]
> > Also, why is `/blocks/height` being called on the Block page?
> 
> `/blocks/height` is used on the block page to make the prev / next block functionality on the header
> 
> <img alt="Screen Shot 2021-04-28 at 11 26 38 AM" width="413" src="https://user-images.githubusercontent.com/1687233/116474746-c0687d00-a82d-11eb-9256-68691c4d603b.png">
> 
> @crussell-figure

Ahh okay.
