### ISSUE TITLE
Mapping issues on governance proposal "Transaction Message or Result" view

### ISSUE THREAD

**Issue by iramiller** [provenance-io/explorer-frontend#67]
## Summary of Bug

Mapping issues on governance proposal "Transaction Message or Result" view

## Version

Current explorer.test.provenance.io

## Steps to Reproduce

View:
https://explorer.test.provenance.io/tx/E5249ED9534C1672B1B0AEFD94173002F7AB940583BF933488CE3FB65732EEF2

- Update time is shown when underlying value is null (`"0001-01-01T00:00:00Z"`)
- Switch Height is empty instead of `1093000`
____

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by webbushka** [comment]
in #90 we redid how the tx msgs are displayed. For now we loop through everything and just print the results. There are a few items we message but not many. I'll close this for now and we can open new items for more massaging in a future release.
