### ISSUE TITLE
Add tooltip/hover text to show actual coin value behind the displayed version

### ISSUE THREAD

**Issue by iramiller** [provenance-io/explorer-frontend#72]
## Summary

Currently the amounts of coins are displayed using the metadata display denom units.  This provides a quick and useful value but sometimes the exact number is desired.  Showing this value in a tooltip would provide this info for those that care about it.

## Proposal

Add a hover/tool tip text with the exact coin amount and denom to be displayed when a user hovers over a coin amount ... or if that is considered bad accessibility perhaps on some of the more important amounts use that little info `i` circle...

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by webbushka** [comment]
@iramiller Because we often format the amount outside of a component, this becomes pretty cumbersome to do everywhere... Is there a specific section of the explorer that you'd consider to have the `more important amounts`?

**Comment by iramiller** [comment]
The only place I would expect to need the precise amount would be on the account page where it lists the "total assets" .. specifically the "total balance" column.  If you are using denom metadata to transform these values here for display then showing the original value as a tooltip or in parenthesis (as space allows) makes sense to me.

**Comment by webbushka** [comment]
How's this?
<img width="1027" alt="Screen Shot 2021-06-14 at 12 56 46 PM" src="https://user-images.githubusercontent.com/1687233/121944653-b8926880-cd07-11eb-8cc5-f0f98af45075.png">

**Comment by iramiller** [comment]
Does that 100,000,000T hide the specific value?  The piece that kicked this all of was @ranadewall trying to use the explorer for some reports that needed to line up to the exact nhash amount.  Seems like we could just show the number in the tooltip with no special units maybe...

**Comment by webbushka** [comment]
@iramiller yeah I can show the full amount instead, in the hover. It's just using the title, so it should also be accessible.

<img width="1060" alt="Screen Shot 2021-06-14 at 1 04 54 PM" src="https://user-images.githubusercontent.com/1687233/121945617-d01e2100-cd08-11eb-81ac-9444c6c7684f.png">
