### ISSUE TITLE
Delegation Panel Showing nhash Amount Instead of Hash

### ISSUE THREAD

**Issue by jdfigure** [provenance-io/explorer-frontend#73]
## Summary of Bug

Delegation panel is showing the nhash amount with a `hash` label: https://explorer.provenance.io/validator/pbvaloper157vsjx6f3pvd0gszvh6q6emc04trpznwqn8wap

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by webbushka** [comment]
Might relate to #37

**Comment by webbushka** [comment]
Fixed by #105
